# Autogenerated - do not edit
FROM hansd/base:latest
MAINTAINER Hans Donner <hans.donner@pobox.com> "https://github.com/hans-d"

RUN add-apt-repository ppa:vbernat/haproxy-1.5; \
    apt-get update; \
    apt-get install -y haproxy
RUN mv /etc/haproxy /etc/haproxy.def && \
    mkdir -p /etc/haproxy

RUN  curl -L https://github.com/hashicorp/consul-haproxy/releases/download/v0.1.1/0.1.1_linux_amd64 > /consul-haproxy && \
  chmod 777 /consul-haproxy

RUN mkdir -p /docker/scripts /docker/templates
ADD common/scripts /docker/scripts

ADD etc /etc

RUN chmod +x --recursive /etc/my_init.d/* /etc/service/*

RUN rm -rf /etc/service/sshd /etc/my_init.d/00_regen_ssh_host_keys.sh

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


EXPOSE 80 8080 9000 443

