#!/bin/bash

status () {
    echo "---> ${@}" >&2
}

status "Make sure we have a config file"
if [ ! -f /etc/haproxy/haproxy.cfg ]; then
    cp -nR /etc/haproxy.def/* /etc/haproxy/.
    echo "Update the default config and restart"
    exit 1
fi

/usr/sbin/haproxy -db -f /etc/haproxy/haproxy.cfg
