#!/bin/sh

if [ -f /tmp/haproxy-reconfig ]; then
    exit
fi

touch /tmp/haproxy-reconfig
sleep 1
rm /tmp/haproxy-reconfig

ls /etc/haproxy/conf.d/*.conf | xargs -L1 sed -e '$s/$/\n/' > /etc/haproxy/haproxy.cfg
